language: node_js
node_js:
  - 10
  - "node"

services:
  - postgresql

before_script:
  - psql -c 'create database ireporter;' -U postgres
  - npm run db-migrate

after_success:
  - npm run coverage
